### ISSUE TITLE
N6 (Nature) code on the AliquotaIVA field

### ISSUE THREAD

**Issue by ClaudioBrocco** [paolodongilli/fatturapa-xsl-southtyrol#1]
Hi, Thank you for this project.

Could you please explain why do you put in the AliquotaIVA field the "N6" string if AliquotaIVA is 0? I think "Natura" value should be in "Natura" field. Is it a legal issue? 

`<xsl:when test="$IVA='0.00' or $IVA='0'">
  <xsl:if test="Natura"><span><xsl:value-of select="Natura" /></span></xsl:if>
</xsl:when>`

**Comment by fertav** [comment]
Hi Claudio

The reason lies in the Italian VAT legislation. If the service is not subject to VAT ($IVA='0'), the reason must be stated. N1 - N7 are the short names.
Here you can read the exact reason (unfortunately only in Italian)

http://fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd
